### PR TITLE
6/29: Build out page for contact me, add validation functions & minor fixes

### PR DESCRIPTION
**Pull request by annemariecabs**
Build out the contact.html & style.css file in preparation for a "Contact Me" form. Server-side of this page is not yet functional. Add validation functions for that form's responses to the Javascript. Fix minor elements of blog (e.g. update some image pathways and title of about page).

Note: Currently, seems to be registering changes from a pull request that has not yet been merged to master in addition to actual changes made. Only new changes begin after add "Feeling Lucky?" button commit.

### CODE REVIEW

**Comment by ykjchen** [comment]
Hey @annemariecabs what branch was `contact-me` created from? The PR would show only changes in the `contact-me` branch if the base brach of this PR was the origin branch.

**Comment by annemariecabs** [comment]
@ykjchen It was (unintentionally) created from the dev branch I believe because I created it while on the dev branch. As such, that's why I believe all these changes are showing up.

**Comment by ykjchen** [comment]
Hey @annemariecabs can you merge master into your contact-me branch? That should help hide some unrelated changes from this PR's diffs.

I think:
git fetch upstream
git checkout origin/master
git pull
git checkout contact-me
git merge origin/master

**Comment by annemariecabs** [comment]
@ykjchen I merged contact-me with the new upstream/master, and I'm going to reopen a new pull request, which should hopefully have only the relevant commits & close this one. Thank you!

**Pull request closed without merging**
